POST http://localhost:8000/events/1/register
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImxldmFuaUBnbWFpbC5jb20iLCJleHAiOjE3MTYzMDkzMTksInVzZXJJZCI6MX0.zYmaywZInch45ML1f1TCzoiErpmy1FXH8cJ2jE5s7vk
